export const candidates = [
  {
    name: 'Christian Lee',
    position: 'Javascript',
    level: 'Senior',
    email: 'bal222@njit.edu',
    salary_expectations: '7500',
    applied: '15.04.2024',
    technology: "Javascrip",
    eval: "top",
    cv: "Top level high rated virtuos",
  },
  {
    name: 'Emily White',
    position: 'Frontend Developer',
    level: 'Mid',
    email: 'emilywhite@example.com',
    salary_expectations: '60000',
    technology: "Javascrip",
    applied: '15.04.2024',
    eval: "top",
    cv: "Top level high rated virtuos",
  },
  {
    name: 'Michael Johnson',
    position: 'Backend Developer',
    level: 'Senior',
    email: 'michaeljohnson@gmail.com',
    salary_expectations: '80000',
    technology: "Javascrip",
    applied: '10.04.2024',
    cv: "Top level high rated virtuos",
    eval: "top"
  },
  {
    name: 'Samantha Brown',
    position: 'Data Scientist',
    level: 'Junior',
    email: 'sam.brown@example.com',
    salary_expectations: '65000',
    applied: '05.03.2024',
    cv: "Top level high rated virtuos",
    technology: "Javascrip",
    eval: "mid"
  },
  {
    name: 'Adam Smith',
    position: 'Full Stack Developer',
    level: 'Senior',
    email: 'adam.smith@company.com',
    salary_expectations: '90000',
    cv: "Top level high rated virtuos",
    applied: '02.02.2024',
    eval: "mid"
  },
  {
    name: 'Jessica Williams',
    position: 'UI/UX Designer',
    technology: "Javascrip",
    level: 'Mid',
    email: 'jessica.williams@example.com',
    salary_expectations: '70000',
    applied: '18.03.2024',
    cv: "Top level high rated virtuos",
    eval: "mid",
  },
  {
    name: 'David Miller',
    position: 'DevOps Engineer',
    level: 'Senior',
    email: 'david.miller@company.com',
    technology: "Javascrip",
    cv: "Top level high rated virtuos",
    salary_expectations: '85000',
    applied: '11.04.2024',
    eval: "mid"
  },
  {
    name: 'Sophia Anderson',
    position: 'Software Engineer',
    level: 'Junior',
    email: 'sophia.anderson@example.com',
    technology: "Javascrip",
    cv: "Top level high rated virtuos",
    salary_expectations: '60000',
    applied: '28.02.2024',
    eval: "mid"
  },
  {
    name: 'Daniel Martinez',
    position: 'Database Administrator',
    level: 'Mid',
    cv: "Top level high rated virtuos",
    email: 'daniel.martinez@company.com',
    salary_expectations: '75000',
    applied: '08.03.2024',
    technology: "Javascrip",
    eval: "mid"
  },
  {
    name: 'Olivia Thompson',
    position: 'Machine Learning Engineer',
    level: 'Senior',
    email: 'olivia.thompson@example.com',
    technology: "Javascrip",
    cv: "Top level high rated virtuos",
    salary_expectations: '95000',
    applied: '14.02.2024',
     eval: "mid"
  }
];