export const employe = [
  {
    "id": 1236,
    "title": "Neues Amt eG",
    "branch": "Mid-Level",
    "date": "Hannover",
    "positions": 4,
    "about": 'Neues Amt eG is an innovative outsourcing company',
    "total": 24,
  },
  {
    "id": 1237,
    "title": "Neues Amt eG",
    "branch": "Mid-Level",
    "date": "Hannover",
    "about": 'Neues Amt eG is an innovative outsourcing company',
    "positions": 4,
    "total": 24,
  },
  {
    "id": 1238,
    "title": "Neues Amt eG",
    "branch": "Mid-Level",
    "date": "Hannover",
    "about": 'Neues Amt eG is an innovative outsourcing company',
    "positions": 4,
    "total": 24,
  },
  {
    "id": 1239,
    "title": "Neues Amt eG",
    "about": 'Neues Amt eG is an innovative outsourcing company',
    "branch": "Mid-Level",
    "date": "Hannover",
    "positions": 4,
    "total": 24,
  },
  {
    "id": 1240,
    "title": "Neues Amt eG",
    "branch": "Mid-Level",
    "about": 'Neues Amt eG is an innovative outsourcing company',
    "date": "Hannover",
    "positions": 4,
    "total": 24,
  },
  {
    "id": 1241,
    "title": "Neues Amt eG",
    "branch": "Mid-Level",
    "date": "Hannover",
    "about": 'Neues Amt eG is an innovative outsourcing company',
    "positions": 4,
    "total": 24,
  },
  {
    "id": 1242,
    "title": "Neues Amt eG",
    "branch": "Mid-Level",
    "date": "Hannover",
    "positions": 4,
    "about": 'Neues Amt eG is an innovative outsourcing company',
    "total": 24,
  },
  {
    "id": 1243,
    "title": "Neues Amt eG",
    "about": 'Neues Amt eG is an innovative outsourcing company',
    "branch": "Mid-Level",
    "date": "Hannover",
    "positions": 4,
    "total": 24,
  },
  {
    "id": 1245,
    "title": "Neues Amt eG",
    "branch": "Mid-Level",
    "about": 'Neues Amt eG is an innovative outsourcing company',
    "date": "Hannover",
    "positions": 4,
    "total": 24,
  }
]